version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/tomato

    steps:
      - checkout
      - run:
          name: Run go mod
          command: |
            go mod download
            go mod vendor
      - run:
          name: Run vet
          command: go vet
      - run:
          name: Run lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status
      - run:
          name: Run staticcheck
          command: |
            go get -u honnef.co/go/tools/cmd/staticcheck
            staticcheck
      - run:
          name: Run tests
          command: go test -v
  modules-update:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/y-yagi/tomato

    steps:
      - checkout
      - run:
          name: Run ci-modules-update
          command: |
            GO111MODULE=off go get -u github.com/y-yagi/ci-modules-update
            ci-modules-update -u y-yagi -r y-yagi/tomato

workflows:
  version: 2
  build:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 22 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - modules-update
